# FROM balenalib/raspberrypi4-64-python:3-build
FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-build

# Copy requirements.txt and scripts folder to /usr/src/app
COPY ./scripts /usr/src/app/scripts
COPY ./requirements.txt /usr/src/app
# Install Python package dependencies in requirements.txt
RUN pip3 install --requirement /usr/src/app/requirements.txt
# Start the i2c bus on debian to make sure the CCS811 sensor works
CMD modprobe i2c-dev && python3 /usr/src/app/scripts/sensor.py